server:
  port: 1024
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data?useSSL=false
    username: root
    password: 1234
  mail:
    host: smtp.163.com
    port: 25
    username: t18713827231@163.com
    password: RWNKORILLAUDXFJE
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #显示邮件发送信息
        debug: true
web:
  upload-path: E:\Idea project\Used-Trading\src\main\resources\static

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.revolver.pojo
  configuration:
    map-underscore-to-camel-case: true

mvc:
  static-path-pattern: /**


alipay:
  appId: 9021000126642711
  appPrivateKey:
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqgbojenL8L8YbJZ2Bai7aAxbRCDwgYl9ctpgXWlpYIPVbIzFRtxvSSoZ24gvfoAj7qJKPZ7+SXPFzXw86AufoB9bLjKC6O739tqyl2pouzFqoHFgZ94efaklOWXylmioL0Z3G02nH75fJiq/HWw0gCgyi032ploHC3TQb905EcCasHP0XikedbaHbpR88ZHOqlRZ5M/gCQRVYWSXGHCPVIZ96h426fSkh5FK0NjNuZrkEHFJBzSbHsSxhg8dG6TkCrjpuEV9hH1uA/W2w/L2nBPbh4G+X31Ji3FseVC/9y0l6xkTBdcvQ7YxygFs4IBczKi0c9evFzcy71hR9/xC0wIDAQAB
  notifyUrl: http://jzrk3e.natappfree.cc/alipay/notify
  returnUrl: http://localhost:8080